doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            enum_email_purpose: Sowapps\SoCore\DBAL\EnumEmailPurposeType
            enum_file_purpose: Sowapps\SoCore\DBAL\EnumFilePurposeType
            enum_file_source: Sowapps\SoCore\DBAL\EnumFileSourceType
            enum_file_storage: Sowapps\SoCore\DBAL\EnumFileStorageType
        mapping_types:
            enum: string
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        resolve_target_entities:
            Sowapps\SoCore\Entity\AbstractUser: App\Entity\User
        dql:
            string_functions:
                # Match against should have the path to the MatchAgainst class created in the previous step
                MATCH: \DoctrineExtensions\Query\Mysql\MatchAgainst
            numeric_functions:
                # For more about spatial functions, see https://github.com/creof/doctrine2-spatial/blob/4e3d8154a23cbb7216f32b38244dce615db6c28b/INSTALL.md
                st_distance_sphere: Sowapps\SoCore\Doctrine\StDistanceSphere
                ln: Sowapps\SoCore\Doctrine\LN
                greatest: Sowapps\SoCore\Doctrine\Greatest
                least: Sowapps\SoCore\Doctrine\Least
                ifnull: Sowapps\SoCore\Doctrine\IfNull # Use \DoctrineExtensions\Query\Mysql\IfNull

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
