name: so-ingenious-demo
services:
    web:
        container_name: web
        build:
            context: ..
            dockerfile: docker/php/Dockerfile
            args:
                PHP_VERSION: "8.2"
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
            # Mount the local project into the container
            - ../:/var/www/html:rw,cached
            # Folder var/ is separated from the project to avoid FS errors
            - so_ingenious_var:/var/www/html/var:rw
            # Folder vendor/ is separated from the project to avoid FS errors
#            - so_ingenious_vendor:/var/www/html/vendor:rw
            # Mount the local certificates to use HTTPS
            - ./certs:/etc/apache2/certs:ro
            # Mount the local sowapps bundles expected by composer.json
            - ../../symfony-so-core-bundle:/var/www/symfony-so-core-bundle:rw,cached
            - ../../symfony-so-log-bundle:/var/www/symfony-so-log-bundle:rw,cached
            - ../../symfony-so-ingenious-bundle:/var/www/symfony-so-ingenious-bundle:rw,cached
        environment:
            APP_ENV: dev
        depends_on:
            - database
            - mailer

    database:
        container_name: database
        image: mariadb:11.4
        restart: always
        environment: # See https://mariadb.com/docs/server/server-management/install-and-upgrade-mariadb/installing-mariadb/binary-packages/automated-mariadb-deployment-and-administration/docker-and-mariadb/mariadb-server-docker-official-image-environment-variables
            MARIADB_ROOT_PASSWORD: root
            # We don't create any app user to use root, so we can create databases by our-self (compatibility with integration tests)
        ports:
            - "3306:3306"
        volumes:
            - so-ingenious-demo_db:/var/lib/mysql

    mailer:
        container_name: mailer
        image: axllent/mailpit
        ports:
            - "1025:1025"
            - "8025:8025"
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - "8081:8080"
        depends_on:
            - database

volumes:
    so-ingenious-demo_db:
    so_ingenious_var:
    so_ingenious_vendor:

